// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransacoesBanco.Models;

#nullable disable

namespace TransacoesBanco.Migrations
{
    [DbContext(typeof(TransaccaoDbContext))]
    partial class TransaccaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TransacoesBanco.Models.Transaccao", b =>
                {
                    b.Property<int>("TransaccaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodigoSWIFT")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("DataTransaccao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Montante")
                        .HasColumnType("int");

                    b.Property<string>("NomeBanco")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("TitularConta")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TransaccaoId");

                    b.ToTable("Transaccoes");
                });
#pragma warning restore 612, 618
        }
    }
}
